version: '3'

services:
        web:
                container_name: optomcalc
                build: .
                command: poetry run python manage.py runserver 0.0.0.0:8000
                ports:
                        - 8000:8000
