version: '3.7'

services:
        web:
                volumes:
                        - ./app/:/usr/src/app/
                        - static:/static
                env_file:
                        - .env
                build: ./app
                ports:
                        - 8000:8000
        nginx:
                build: ./nginx
                volumes:
                        - static:/static
                depends_on:
                        - web
volumes:
        static:
