version: '3.7'

services:
        db:
                image: 'postgres:latest'
                ports:
                        - "5432:5432"
                env_file:
                        - ./optomcalc/optomcalc/.env
                volumes:
                        - ./db-data/:/var/lib/postgresql/data/
        web:
                container_name: web
                volumes:
                        - static:/usr/src/optomcalc/optomcalc/static
                        - .:/usr/src/
                env_file:
                        - ./optomcalc/optomcalc/.env
                build: .
                working_dir: /usr/src/optomcalc/
                command: sh -c "./entrypoint.sh"
                ports:
                        - "8000:8000"
                depends_on:
                        - db
volumes:
        static:
